### PR TITLE
Add CMakeLists file for sample plugin

### PR DESCRIPTION
**Pull request by BlackPhrase**
* Fixed akane again
* atexit_handler is broken and outside of VS the app shuts down right after opening (it was intended to fix that)

### CODE REVIEW

**Comment by SuzuNakamura** [comment]
move cstring header into akane_util.h will be better(I move it some days ago but changes are overwrote by old branch's code after my force pulling operation)

**Comment by SuzuNakamura** [comment]
and,I think we don't need to pause the app on every exit,I will add startup parameter options to enable this behavior in a few days,so I disbale the handler temporarily.

**Comment by BlackPhrase** [comment]
>change header to cstddef and move this line into  akane_util.h will be better(I move it a few days ago but changes are  overwrote by old branch's code after my force pulling operation and I  didn't notice that)

It's used by the whole library
Almost every other file uses size_t so it definitely will be better to place it into the main akane header

**Comment by SuzuNakamura** [comment]
>It's used by the whole library
Almost every other file uses size_t so it definitely will be better to place it into the main akane header
If other headers are meant to be used separately then everyone should include the file

akane_util is included by add basic header in akane,it's no need to place cstddef in collection header.

>It doesn't work even in debug build

There's no ploblem in Visual Studio 2017 with Windows SDK 10.0.17134.0 and handler works well.I will test handler later in Debian with Clang++ compiler.

**Comment by BlackPhrase** [comment]
>There's no ploblem in Visual Studio 2017 with Windows SDK 10.0.17134.0 and handler works well.I will test handler later in Debian with Clang++ compiler.

It doesn't work using CMake and MinGW, should I enable the debugging option?

**Comment by BlackPhrase** [comment]
Also, I don't recommend to modify (remove the commits) the master branch history when working with collaborators
Master should remain the same for everyone and modified only by pull requests
There is a revert function in git that will create a new commit that will cancel the previous commit(s) changes
That is the recommended way when working on a project with someone else

**Comment by SuzuNakamura** [comment]
>It doesn't work using CMake and MinGW, should I enable the debugging option?

No, there's no other association with this.

>Also, I don't recommend to modify (remove the commits) the master branch history when working with collaborators
Master should remain the same for everyone and modified only by pull requests
There is a revert function in git that will create a new commit that will cancel the previous commit(s) changes
That is the recommended way when working on a project with someone else

Sorry for my experience lacking of this.I wlll open a branch to work for now.

**Comment by BlackPhrase** [comment]
>Sorry for my experience lacking of this.I wlll open a branch to work for now.

Nah, its ok
Usually, the master branch contains the latest stable state (suitable for release) of the codebase
And the work on the further improvements is going on inside the dev branch
There also might be a stabilization branch which will be used as an intermediate level between dev and master branches
There is also a [GitFlow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) branching model which recommends developers to create custom branches to work on features and bugfixes/hotfixes

**Comment by SuzuNakamura** [comment]
I correct all compiling issue in debian witn g++ and make a test with AtExitHandler enabled, it's works well.

**Comment by BlackPhrase** [comment]
Nice
And you don't need to merge with master after every change, it only should contain the stable buildable state of the codebase, it might a bit outdated
You can work in your testing branch and periodically merge with master (once in a day/week/month/whatever) if everything is fine
Other developers will use the testing branch as a base for their changes, in such case
That's, of course, up to you to decide about your merging/branching strategy, I'm only telling about what other developers are using

**Pull request closed without merging**
